# server
server:
  port: 8080
  servlet:
    context-path: /blog
# spring
spring:
  # springmvc
  application:
    name: mk-blog
  # datasource
  datasource:
    url: jdbc:p6spy:mysql://122.52.142.2222:3306/blog?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: MKmysql123456.
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 支持emoji表情配置
      connectionInitSqls: set names utf8mb4
      # 初始化连接池个数
      initial-size: 5
      # 最大连接池个数
      max-active: 20
      # 最小连接池个数
      min-idle: 5
      # 配置获取连接等待超时的时间，单位毫秒
      max-wait: 5000
      # 获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      # 归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      # 申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # 是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: false
      validation-query: SELECT 1 FROM DUAL
      # 监控统计用的filter:stat
      # 日志用的filter:log4j
      # 防御sql注入的filter:wall
      filters: stat,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        #是否启用StatViewServlet（监控页面）默认值为false
        enabled: true
        login-username: admin
        login-password: admin1314
        # 添加IP白名单
        allow: 127.0.0.1
        url-pattern: /druid/*
        reset-enable: false
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        deny: 192.168.0.1
      # Druid和Spring关联监控配置
      aop-patterns: pers.mk.blog.service.*
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: "/*"
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        profile-enable: true
  # redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 15
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 3
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
# spring-doc
springdoc:
  api-docs:
    enabled: true
  # 设置文档默认不展开
  swagger-ui:
    docExpansion: none

